### ISSUE TITLE
euca-describe-addresses

### ISSUE THREAD

**Issue by lwade** [eucalyptus/eucalyptus-sosreport-plugins#50]
Hey @hspencer77!

euca-describe-addresses-verbose returns nothing.  euca-describe-addresses is the desired command.  So we are not picking up anything from the sosreport plugin as we are running the former.  Tbh this is probably a bug in Euca.

**Comment by hspencer77** [comment]
@lwade i am closing this out since it seems to no longer be an issue in 4.0.x and 4.1.0.
