### ISSUE TITLE
FR: Add subscription cert information

### ISSUE THREAD

**Issue by lwade** [eucalyptus/eucalyptus-sosreport-plugins#67]
If the user is a customer, they'll most likely have the eucalyptus release RPM installed.  If they have this installed, we'll have the cert installed in /etc/pki/tls/certs/eucalyptus-enterprise.crt.  I would be good if we could collect their subscription information using something like this:

openssl x509 -text -in /etc/pki/tls/certs/eucalyptus-enterprise.crt | grep -A 2 Validity

maybe there is a python library for pulling fields from a cert directly (I've not checked) ?

**Comment by hspencer77** [comment]
Fixed by PR https://github.com/eucalyptus/eucalyptus-sosreport-plugins/pull/80
