### ISSUE TITLE
Include SELinux policies in sos report

### ISSUE THREAD

**Issue by tbeckham** [eucalyptus/eucalyptus-sosreport-plugins#99]
We should gather what SELinux modules are loaded and if possible grab the policy packages or files for inclusion in SOS reports

**Comment by quadespresso** [comment]
There appears to be an 'selinux' module which exists as part of the core sosreport package.

Could you test "sosreport --batch -o selinux" and check whether this provides what you're looking for?

**Comment by tbeckham** [comment]
@quadespresso that works perfectly. Thanks!
